#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""Instance Visualizer Script."""

import sys
import os

# Add local visualizer module path before any installed visualizer package.
sys.path.insert(0, os.path.join(os.path.dirname(os.path.realpath(__file__)), '..'))

from visualizer.control import VizControl

#main
def main():
    control = VizControl()
    control.run()

if __name__ == '__main__':
    sys.exit(main())
